apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
name: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
releaseName: demo
# version:
# valuesInline:
